"""initial migration

Revision ID: 75baaaaec506
Revises: 
Create Date: 2026-03-04 12:05:36.490395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75baaaaec506'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amortization_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_amortization_due_date'))
        batch_op.drop_index(batch_op.f('idx_amortization_loan_id'))

    op.drop_table('amortization_schedule')
    op.drop_table('chart_of_accounts')
    op.drop_table('payment_allocations')
    op.drop_table('journal_entries')
    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_journal_lines_entry_id'))

    op.drop_table('journal_entry_lines')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_payments_loan_id'))

    op.drop_table('payments')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_loans_customer_id'))
        batch_op.drop_index(batch_op.f('idx_loans_status'))

    op.drop_table('loans')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('document_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('risk_classification',
               existing_type=postgresql.ENUM('A', 'B', 'C', 'D', 'E', name='risk_classification_enum'),
               type_=sa.String(length=1),
               nullable=True,
               existing_server_default=sa.text("'A'::risk_classification_enum"))
        batch_op.drop_index(batch_op.f('idx_customers_document_number'))
        batch_op.drop_constraint(batch_op.f('uq_customer_document'), type_='unique')
        batch_op.create_unique_constraint(None, ['document_number'])
        batch_op.drop_column('address')
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('business_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_customer_document'), ['document_type', 'document_number'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_customers_document_number'), ['document_number'], unique=False)
        batch_op.alter_column('risk_classification',
               existing_type=sa.String(length=1),
               type_=postgresql.ENUM('A', 'B', 'C', 'D', 'E', name='risk_classification_enum'),
               nullable=False,
               existing_server_default=sa.text("'A'::risk_classification_enum"))
        batch_op.alter_column('city',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('document_type',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    op.create_table('loans',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('requested_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('approved_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('interest_rate', sa.NUMERIC(precision=7, scale=4), autoincrement=False, nullable=False),
    sa.Column('interest_rate_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('term_months', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amortization_type', postgresql.ENUM('CUOTA_FIJA', 'ABONO_CONSTANTE_CAPITAL', name='amortization_type_enum'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('RADICADO', 'APROBADO', 'DESEMBOLSADO', 'AL_DIA', 'EN_MORA', 'REESTRUCTURADO', 'CASTIGADO', 'PAGADO', name='loan_status_enum'), server_default=sa.text("'RADICADO'::loan_status_enum"), autoincrement=False, nullable=False),
    sa.Column('filing_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('disbursement_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('outstanding_principal', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('approved_amount > 0::numeric', name=op.f('loans_approved_amount_check')),
    sa.CheckConstraint('requested_amount > 0::numeric', name=op.f('loans_requested_amount_check')),
    sa.CheckConstraint('term_months > 0', name=op.f('loans_term_months_check')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('loans_customer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('loans_pkey'))
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_loans_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_loans_customer_id'), ['customer_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('loan_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('payment_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('amount_paid', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('payment_method', postgresql.ENUM('PSE', 'CONSIGNACION', 'DEBITO_AUTOMATICO', 'CORRESPONSAL_BANCARIO', name='payment_method_enum'), autoincrement=False, nullable=False),
    sa.Column('is_applied', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('amount_paid > 0::numeric', name=op.f('payments_amount_paid_check')),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('payments_loan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey')),
    sa.UniqueConstraint('payment_reference', name=op.f('uq_payment_reference'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_payments_loan_id'), ['loan_id'], unique=False)

    op.create_table('journal_entry_lines',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('journal_entry_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('entry_type', postgresql.ENUM('DEBITO', 'CREDITO', name='accounting_entry_type_enum'), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.CheckConstraint('amount > 0::numeric', name=op.f('journal_entry_lines_amount_check')),
    sa.ForeignKeyConstraint(['account_id'], ['chart_of_accounts.id'], name=op.f('journal_entry_lines_account_id_fkey')),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name=op.f('journal_entry_lines_journal_entry_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('journal_entry_lines_pkey'))
    )
    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_journal_lines_entry_id'), ['journal_entry_id'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('entry_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('journal_entries_pkey'))
    )
    op.create_table('payment_allocations',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('concept', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('allocated_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.CheckConstraint('allocated_amount >= 0::numeric', name=op.f('payment_allocations_allocated_amount_check')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('payment_allocations_payment_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('payment_allocations_pkey'))
    )
    op.create_table('chart_of_accounts',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('account_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('account_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('nature', postgresql.ENUM('DEBITO', 'CREDITO', name='accounting_entry_type_enum'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('chart_of_accounts_pkey')),
    sa.UniqueConstraint('account_code', name=op.f('chart_of_accounts_account_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('amortization_schedule',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('loan_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('installment_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('principal_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('interest_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('life_insurance_amount', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('other_charges', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_installment', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('remaining_principal', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_paid', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('amortization_schedule_loan_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('amortization_schedule_pkey')),
    sa.UniqueConstraint('loan_id', 'installment_number', name=op.f('uq_loan_installment'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('amortization_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_amortization_loan_id'), ['loan_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_amortization_due_date'), ['due_date'], unique=False)

    # ### end Alembic commands ###
